name: retog
description: A new Flutter project.
version: 1.4.5+33

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.0
  fk_user_agent: ^2.0.1
  pub_semver: ^2.0.0
  path_provider: ^2.0.2
  sqflite: ^2.0.0
  barcode_scan2:  ^4.2.0
  sentry_flutter: ^5.0.0
  shared_preferences: ^2.0.6
  package_info: ^2.0.2
  flutter_typeahead: ^3.2.4
  flutter_sticky_header: ^0.6.1
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/data/schema.sql
    - .env
