name: retog
description: Приложение для создания возвратов
publish_to: 'none'
version: 1.6.0+36

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  drift: ^2.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.7.0
  mask_text_input_formatter: ^2.4.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.9
  provider: ^6.0.5
  pub_semver: ^2.1.1
  quiver: ^3.0.1
  sentry_flutter: ^7.7.0
  sqlite3_flutter_libs: ^0.5.0
  u_app_utils:
    git:
      url: git@github.com:Unact/u_app_utils.git
      ref: 8c87446

dev_dependencies:
  build_runner: ^2.4.5
  drift_dev: ^2.9.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
