name: retog
description: A new Flutter project.
version: 1.2.0+22

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: any
  cupertino_icons: any
  path_provider: any
  sqflite: any
  intl: any
  barcode_scan: any
  sentry: any
  dotenv: any
  shared_preferences: any
  device_info: any
  package_info: any
  flutter_typeahead: any
  flutter_sticky_header: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/data/schema.sql
    - .app_env
